server {
    listen 80;

    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header Cache-Control "no-store";
    }

    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;

        add_header Cache-Control "no-cache";
    }
}