spring.datasource.url=jdbc:postgresql://145.220.72.157:5433/stakeit_db?sslmode=disable
spring.datasource.username=stakeit_user
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver
